### ISSUE TITLE
Patch stopped working

### ISSUE THREAD

**Issue by edublancas** [jaredculp/iterm2-borderless-padding#10]
Hi, the patch stopped working. I'm getting the top bar now.

<img width="714" alt="captura de pantalla 2016-08-23 a las 9 17 58 p m" src="https://cloud.githubusercontent.com/assets/989250/17916237/1b8c68f4-6977-11e6-82ad-2febea540a79.png">

**Comment by jmmendivil** [comment]
Dude, check your setup, I just installed it 5min ago

![screen shot 2016-08-25 at 8 20 24 pm](https://cloud.githubusercontent.com/assets/1274534/17991111/950ddbd2-6b01-11e6-9bb3-315cb056b9f9.png)

**Comment by edublancas** [comment]
My bad, I actually tried on two computers and got the same result. I'll update if I find what happened.
