### ISSUE TITLE
Full screen has tiny space around window.

### ISSUE THREAD

**Issue by cyfyifanchen** [jaredculp/iterm2-borderless-padding#11]
I have been using this iTerm almost a year, and I absolutely like the look of it. However, every time when I maximize screen, there are tiny spaces around the window. It bugged the crap out of me. Any ideas how to get rid of those?

**Comment by jaredculp** [comment]
You mean the padding?

Edit: oh I know what you mean. I usually just full-screen the app.

**Comment by cyfyifanchen** [comment]
no, not the padding.

**Comment by cyfyifanchen** [comment]
![screen shot 2016-10-13 at 4 02 15 pm](https://cloud.githubusercontent.com/assets/2340896/19368681/792b0af6-915e-11e6-8825-dbaeaadcaed7.png)

**Comment by cyfyifanchen** [comment]
It's really hard to tell unless you try it.

**Comment by cyfyifanchen** [comment]
This happens in original iTerm as well. I was able to set the width and height more than the window  then center it. Now, I am on Sierra, doesn't work anymore. The space only there when maximize the window.

**Comment by jaredculp** [comment]
This functionality now lives upstream, so repo is now deprecated, see README.
