### ISSUE TITLE
Build Fail "Error 65"

### ISSUE THREAD

**Issue by Zarezz** [jaredculp/iterm2-borderless-padding#12]
![screen shot 2016-10-22 at 11 32 16 pm](https://cloud.githubusercontent.com/assets/12651561/19623969/e7decd0e-98af-11e6-80dc-63ca5856f5ba.png)

Every time the install.sh is run I receive this error.

**Comment by jaredculp** [comment]
This functionality now lives upstream, so repo is now deprecated, see README.
