### ISSUE TITLE
I tried installing this and not sure if this is the cause of a quote added to each new opened session

### ISSUE THREAD

**Issue by nikivdev** [jaredculp/iterm2-borderless-padding#13]
Now when I open any new session in iTerm I get a quote that comes with the session : 

![2016-11-02 at 13 40](https://cloud.githubusercontent.com/assets/6391776/19929078/ef2e07c8-a101-11e6-9721-bf168cb2a72b.png)

I don't think I had this before. Is this somehow related to this script I downloaded and ran?

And if so, how can I remove it?

**Comment by jaredculp** [comment]
Shouldn't be.

**Comment by jaredculp** [comment]
This functionality now lives upstream, so repo is now deprecated, see README.
