### ISSUE TITLE
Cannot be moved around with Moom

### ISSUE THREAD

**Issue by dislick** [jaredculp/iterm2-borderless-padding#16]
Hey,

I'm using [Moom](https://manytricks.com/moom/) as a window manager and it can't move/resize the new iTerm2.app. Is there any way I can make this work? This is most likely happening because the window type is changed.

Thanks.

**Comment by dislick** [comment]
Heads up for other people with this issue:

If you can live without the borderless feature, [use this patch file instead](https://github.com/dislick/iterm2-borderless-padding).

**Comment by ghost** [comment]
@dislick I use Moom as well and this works great, thanks!

**Comment by jaredculp** [comment]
This functionality now lives upstream, so repo is now deprecated, see README.
