### ISSUE TITLE
Bottom margin only?

### ISSUE THREAD

**Issue by petemill** [jaredculp/iterm2-borderless-padding#17]
Do you know of a way to patch the code in order to have a different value for vertical margin at the bottom and the top? Thanks!

**Comment by jaredculp** [comment]
You can do this in the latest nightly's of iterm2

**Comment by petemill** [comment]
Thanks @jaredculp I've just installed nightly and as far as I can see there's only an option for a combined 'top and bottom' space. Do have any ideas of whether a patch could easily be applied to split the top and bottom variables?
