### ISSUE TITLE
How to enable borderless padding in latest iterm? 

### ISSUE THREAD

**Issue by davidawad** [jaredculp/iterm2-borderless-padding#19]
The docs don't make it very clear how exactly to enable this since this patch is deprecated. 

an explanation or some screenshots in the readme would be helpful. 

Thanks!

**Comment by dominiklohmann** [comment]
It's in the iTerm2 settings now (not sure if on stable, but it definitely is in the nightly release).

<img width="1130" alt="screen shot 2017-01-17 at 04 13 04" src="https://cloud.githubusercontent.com/assets/4488655/22006433/4724d444-dc6b-11e6-96b8-6f6ae1e1f801.png">

**Comment by yogasukma** [comment]
how do you get the nightly build?

I use 3.0.13 but still didn't see the options. Just top and right. 

![screen shot 2017-02-09 at 2 44 30 pm](https://cloud.githubusercontent.com/assets/1949957/22772221/68e6c56a-eed6-11e6-97bb-06b123f71d02.png)

**Comment by dominiklohmann** [comment]
https://www.iterm2.com/downloads.html

At the very bottom there is a "Nightly Builds" section. Use on your own risk.
