### ISSUE TITLE
Some text in padding/Cursor doesn't display in first line

### ISSUE THREAD

**Issue by WatermelonDriveway** [jaredculp/iterm2-borderless-padding#2]
First off, thanks for putting this together, the padding looks wonderful, just figured I'd point out a few things I've noticed.

Whenever I run tmux, this line gets put up into the padding.
http://a.pomf.hummingbird.moe/olzdjh.png
It goes away when I ^D out of tmux and run it again.

Also the first line in any term window's cursor doesn't show up. 

Neither of these are too big of a deal, but I though you might like to know.  Thanks!

**Comment by fsegouin** [comment]
+1 on this one

**Comment by jaredculp** [comment]
This functionality now lives upstream, so repo is now deprecated, see README.
