### ISSUE TITLE
Not an issue, but a question.

### ISSUE THREAD

**Issue by Auratelience** [jaredculp/iterm2-borderless-padding#20]
Where did you get you `/bin/colourtest` from? It looks really nice.
TIA

**Comment by ajimae** [comment]
Hi @Auratelience 

Save the below script into a file called `colortest.sh`.

```bash
#!/bin/sh

# Usage
# colortest

DOTS='•••'
printf "\n                 40m     41m     42m     43m     44m     45m     46m     47m\n";
for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m'; do
  FG=${FGs// /}
  printf " $FGs \033[$FG  $DOTS  "
  for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
    printf "$EINS \033[$FG\033[$BG  $DOTS  \033[0m";
  done
  printf "\n"
done
printf "\n"
unset -v DOTS
```

Then execute it as `bash colortest.sh` in your terminal.
![Screen Shot 2022-09-03 at 03 04 47](https://user-images.githubusercontent.com/32770340/188249808-0f45c21d-1b63-4c39-ad88-bc60b87bd5d3.png)

**Comment by ajimae** [comment]
![Screen Shot 2022-09-03 at 03 05 52](https://user-images.githubusercontent.com/32770340/188249832-8bd2af63-4dd0-4f0a-97ec-ff75193d0c18.png)

**Comment by Auratelience** [comment]
Cool. Thanks.
