### ISSUE TITLE
Scrollbar always showing up

### ISSUE THREAD

**Issue by imjakechapman** [jaredculp/iterm2-borderless-padding#5]
First off, love this beautiful borderless version of iTerm so kudos to you.

I'm having an issue out of nowhere with the window always showing the scrollbar. I haven't changed any settings or anything but can't figure out exactly what's causing it. 

Is there a way of debugging it? Or possible know the issue?

**Comment by XYTYX** [comment]
+1 on this issue, exactly the same issue as above.

**Comment by XYTYX** [comment]
Found a fix, it's as simple as going into your iTerm preferences, and there's a hide scroll bar option under appearance.
