### ISSUE TITLE
Maximising still leaves some space around

### ISSUE THREAD

**Issue by dhruvasagar** [jaredculp/iterm2-borderless-padding#6]
Hi, I love how this looks :), just what I needed. But when I maximise the window, I still see a few pixels space around the window, just a little distracting for me, was wondering if there was a way to remove that ?

**Comment by rafalio** [comment]
Maybe changing MARGIN and VMARGIN to 0 would work?

**Comment by dhruvasagar** [comment]
No I meant space outside the iterm2 window.

**Comment by edublancas** [comment]
This is an iTerm issue since an unpatched version still leaves some right and down margin outside the window

**Comment by jaredculp** [comment]
@dhruvasagar just run the app in full screen mode?

**Comment by dhruvasagar** [comment]
I don't like mac's full screen at all. I like having the terminal in all workspaces at all times, if I could full screen like in linux it would be better. Although if I did use fullscreen, this project wouldn't really be required.

**Comment by jaredculp** [comment]
This isn't something I can fix for you.

**Comment by dhruvasagar** [comment]
Yea sure, np. Thanks for the work though I love without the borders even with the small space around :)

**Comment by edublancas** [comment]
In case anyone is interested, disabling the margin is possible in iTerm 2.9+:

> In 2.9+ (currently the beta version), you can turn on Prefs > Advanced > Terminal windows resize smoothly to turn off snap-to-grid and use all the space.

[More info here.](https://github.com/sdegutis/mjolnir/issues/562)

**Comment by dhruvasagar** [comment]
Thanks a ton, this works! I tried it with version 3.0.20160730
