### ISSUE TITLE
Patch failed

### ISSUE THREAD

**Issue by carlosdagos** [jaredculp/iterm2-borderless-padding#7]
With iterm2 from master

```
❯ git apply ../0001-Remove-borders-add-padding.patch 
error: patch failed: sources/PseudoTerminal.m:355
error: sources/PseudoTerminal.m: patch does not apply
```

**Comment by carlosdagos** [comment]
I fixed it, so you can update yours as well ;)

https://gist.github.com/charlydagos/2327b909a385da87f3516918b8b5723e

**Comment by jaredculp** [comment]
Fixed in the latest commit to master. Simply had a patch conflict so I updated the install script to be fixed to a single SHA which should prevent this from happening in the future.
